CREATE TABLE SUCURSALES
(
NUM_SUCURSAL NUMBER PRIMARY KEY,
DIRECCION VARCHAR2(30),
ACTIVO NUMBER(*,2)
);

CREATE TABLE CLIENTES
(
DNI VARCHAR2(9) PRIMARY KEY,
NOMBRE VARCHAR2(30),
TELEFONO NUMBER(9),
CORREO VARCHAR2(30),
DIRECCION VARCHAR2(30),
NUM_SUCURSAL NUMBER REFERENCES SUCURSALES
);

CREATE TABLE EMPLEADOS
(
DNI_EMPLE VARCHAR2(9) PRIMARY KEY,
NOMBRE VARCHAR2(30),
NUM_EMPLE NUMBER,
TELEFONO NUMBER(9)
);

CREATE TABLE CUENTAS
(
NUM_CUENTA NUMBER PRIMARY KEY,
DNI_TITULAR VARCHAR2(9) REFERENCES CLIENTES,
DNI_COTITULAR VARCHAR2(9) REFERENCES CLIENTES,
FECHA_APERTURA DATE,
TIPO VARCHAR2(30),
SALDO NUMBER(*,2)
);

CREATE TABLE APERTURAS
(
NUM_CUENTA NUMBER,
DNI VARCHAR2(9)
);