DROP TABLE ALUMNOS CASCADE CONSTRAINTS;
DROP TABLE ASIGNATURAS CASCADE CONSTRAINTS;
DROP TABLE NOTAS CASCADE CONSTRAINTS;

CREATE TABLE ALUMNOS
(
DNI VARCHAR2(9) CONSTRAINT PK_ALUMNOS PRIMARY KEY,
NOMBRE VARCHAR2(30),
APELLIDO VARCHAR2(30)
);

CREATE TABLE ASIGNATURAS
(
COD_ASIGNATURA NUMBER CONSTRAINT PK_ASIGNATURAS PRIMARY KEY,
NOM_ASIGNATURA VARCHAR2(30) NOT NULL UNIQUE
);

CREATE TABLE NOTAS
(
DNI VARCHAR2(9) REFERENCES ALUMNOS, -- FORMA 1 DE METER FOREIGN KEY
COD_ASIGNATURA NUMBER,
NOTA NUMBER(4,2),
CONSTRAINT PK_NOTAS PRIMARY KEY (DNI,COD_ASIGNATURA),
CONSTRAINT FK_NOTAS_ASIG FOREIGN KEY (COD_ASIGNATURA) REFERENCES ASIGNATURAS -- FORMA 2 DE METER FOREIGN KEY
);

INSERT INTO ASIGNATURAS VALUES (1,'MARCAS');
INSERT INTO ASIGNATURAS VALUES (2,'BBDD');

INSERT INTO ALUMNOS VALUES ('12345678A','PEPE','PEREZ');
INSERT INTO ALUMNOS VALUES ('11122233A','ANA','PEREZ');

INSERT INTO NOTAS VALUES ('12345678A',1,9);
INSERT INTO NOTAS VALUES ('12345678A',2,7);
INSERT INTO NOTAS VALUES ('11122233A',1,9);
INSERT INTO NOTAS VALUES ('11122233A',2,9);

SELECT * FROM ASIGNATURAS;
SELECT * FROM NOTAS;
SELECT * FROM ALUMNOS;