-- MOSTRAR EL APELLIDO SEGUIDO DE '* *' SEGUIDO DE LOS TRES PRIMEROS CARACTERES DEL OFICIO DE LOS EMPLEADOS DEL DEPARTAMENTO DE CONTABILIDAD
SELECT APELLIDO || '* *' || SUBSTR(OFICIO,1,3)
  FROM DEPART JOIN EMPLE ON EMPLE.DEPT_NO = DEPART.DEPT_NO
    WHERE DNOMBRE = 'CONTABILIDAD';
    
--MOSTRAR EL NOMBRE DE LAS ATRACCIONES EN MAYÚSCULAS SEGUIDO DE LA ZONA EN MINÚSCULAS DE LAS ATRACCIONES QUE NO HAN TENIDO NUNCA AVERÍAS
SELECT UPPER(NOM_ATRACCION) || ' ' || LOWER(NOM_ZONA)"ATRACCIONES"
  FROM ATRACCIONES
    WHERE ATRACCIONES.COD_ATRACCION NOT IN (SELECT COD_ATRACCION FROM AVERIAS_PARQUE);
    
--MOSTRAR LAS ATRACCIONES QUE TIENEN MÁS DE 8 CARACTERES EN EL NOMBRE Y MÁS DE 8 CARACTERES EN EL NOMBRE DE LA ZONA
SELECT NOM_ATRACCION
  FROM ATRACCIONES
    WHERE LENGTH(NOM_ATRACCION)>=8 AND LENGTH(NOM_ZONA)>=8;
    
--MOSTRAR EL NOMBRE DE LAS ATRACCIONES ACTUALMENTE AVERIADAS EN MINUSCULAS Y SACAR SOLO LOS TRES PRIMEROS CARACTERES DEL NOMBRE Y EL ULTIMO CARACTER DE SU CODIGO
SELECT LOWER(SUBSTR(NOM_ATRACCION,1,3)) || SUBSTR(COD_ATRACCION,-1,1) 
  FROM ATRACCIONES
    WHERE COD_ATRACCION IN (SELECT COD_ATRACCION FROM AVERIAS_PARQUE WHERE FECHA_ARREGLO IS NULL);

 --MOSTRAR EL NOMBRE DE LA ATRACCIÓN CON MÁS CARACTERES TIENE 
 SELECT NOM_ATRACCION
  FROM ATRACCIONES
    WHERE LENGTH(NOM_ATRACCION)= (SELECT MAX(LENGTH(NOM_ATRACCION)) FROM ATRACCIONES);
    
 --MOSTRAR EL TELÉFONO DE LOS ALUMNOS DE MADRID QUE TIENEN SUSPENSAS DE FORMA 999-999-999
SELECT SUBSTR(TELEF,1,3)||'-'||SUBSTR(TELEF,4,3)||'-'||SUBSTR(TELEF,7,3)
  FROM ALUMNOS
    WHERE DNI IN (SELECT DNI FROM NOTAS WHERE NOTA < 5);
    
--MOSTRAR LAS ATRACCIONES QUE ESTAN AVERIADAS ACTUALMENTE DEL SIGUIENTE MODO: NOMBREATRACCION(ZONA): X DIAS ESTROPEADAS
SELECT NOM_ATRACCION||'('||NOM_ZONA||'):'||TRUNC(SYSDATE-FECHA_FALLA)||' DIAS ESTROPEADAS'
  FROM ATRACCIONES JOIN AVERIAS_PARQUE ON AVERIAS_PARQUE.COD_ATRACCION = ATRACCIONES.COD_ATRACCION
    WHERE ATRACCIONES.COD_ATRACCION IN (SELECT COD_ATRACCION FROM AVERIAS_PARQUE WHERE FECHA_ARREGLO IS NULL);
    
--MOSTRAR EL NOMBRE DE LA ATRACCION SEGUIDO DE LOS TRES PRIMEROS CARACTERES DE SU ZONA DE LA QUE MAS DINERO HA COSTADO ARREGLAR
SELECT NOM_ATRACCION || ' ' || UPPER(SUBSTR(NOM_ZONA, 1, 3))
  FROM ATRACCIONES
    WHERE COD_ATRACCION IN (SELECT COD_ATRACCION FROM AVERIAS_PARQUE WHERE COSTE_AVERIA = (SELECT MAX(COSTE_AVERIA) FROM AVERIAS_PARQUE WHERE COD_ATRACCION LIKE 'A%'));