--TABLA DE DEPART Y EMPLE
--APELLIDO, SALARIO Y LOC DEL DEPT DE CONTABILIDAD
SELECT APELLIDO, SALARIO, LOC
  FROM DEPART JOIN EMPLE ON EMPLE.DEPT_NO=DEPART.DEPT_NO
    WHERE DNOMBRE='CONTABILIDAD';
    
--APELLIDO, SALARIO Y DNOMBRE DE DEPTS QUE NO ESTAN EN SEVILLA
SELECT APELLIDO, SALARIO, DNOMBRE
  FROM DEPART JOIN EMPLE ON EMPLE.DEPT_NO=DEPART.DEPT_NO
    WHERE LOC!='SEVILLA';
    
--EMP_NO Y DNOMBRE DE EMPLEADOS CON SALARIOS MAS 1500 ORDENADOS POR DEPT Y SALARIO
SELECT EMP_NO, DNOMBRE
  FROM DEPART JOIN EMPLE ON EMPLE.DEPT_NO=DEPART.DEPT_NO
    WHERE SALARIO>1500
      ORDER BY EMPLE.DEPT_NO, SALARIO;
      
--TABLA DE ASIGNATURAS, NOTAS Y ALUMNOS
--APENOM, DNI, POBLA Y NOMBRE DE ASIGNATURA DE ALUMNOS QUE HAN SUSPENDIDO
--CON EL CODIGO Y NOTA
SELECT APENOM, ALUMNOS.DNI, POBLA, NOMBRE, NOTAS.COD, NOTA
  FROM ASIGNATURAS, ALUMNOS, NOTAS
    WHERE ALUMNOS.DNI=NOTAS.DNI
      AND NOTAS.COD=ASIGNATURAS.COD
      AND NOTA<5;
      
--NOMBRE Y COD DE NOTAS DE 7 O 8
SELECT NOMBRE, NOTAS.COD
  FROM ASIGNATURAS JOIN NOTAS ON ASIGNATURAS.COD=NOTAS.COD
    WHERE NOTA>=7
      AND NOTA<=8;
      
--APENOM DE NOTA ENTRE 6 Y 8 EN BBDD
SELECT APENOM, NOTAS.NOTA
  FROM ASIGNATURAS, ALUMNOS, NOTAS
    WHERE ALUMNOS.DNI=NOTAS.DNI
      AND NOTAS.COD=ASIGNATURAS.COD
      AND NOTA>=6
      AND NOTA<=8
      AND NOMBRE='BBDD';
      
--NOMBRES DE ALUMNOS DE MADRID CON SUSPENSO
SELECT DISTINCT APENOM
  FROM ALUMNOS, ASIGNATURAS, NOTAS
    WHERE ALUMNOS.DNI=NOTAS.DNI
      AND NOTAS.COD=ASIGNATURAS.COD
      AND NOTA<5;
      
--NOMBRES DE ALUMNOS ORDENADOS Y ASIGNATURAS APROBADAS
SELECT APENOM, NOMBRE
  FROM ALUMNOS, ASIGNATURAS, NOTAS
    WHERE ALUMNOS.DNI=NOTAS.DNI
      AND NOTAS.COD=ASIGNATURAS.COD
      AND NOTA>5
        ORDER BY APENOM;
        
--TABLA DE PARQUE DE ATRACCIONES
--NOMBRE DE ATRACCIONES CON AVER�AS
SELECT NOM_ATRACCION
  FROM ATRACCIONES JOIN AVERIAS_PARQUE ON ATRACCIONES.COD_ATRACCION=AVERIAS_PARQUE.COD_ATRACCION
    WHERE FECHA_ARREGLO IS NULL;
    
--NOMBRE DE EMPLEADO QUE TIENE QUE ARREGLAR
SELECT NOM_EMPLEADO
  FROM EMPLE_PARQUE JOIN AVERIAS_PARQUE ON EMPLE_PARQUE.DNI_EMPLE=AVERIAS_PARQUE.DNI_EMPLE
    WHERE FECHA_ARREGLO IS NULL;
    
--MOSTRAR ZONAS JUNTO CON SUS ENCARGADOS ORDENADOS POR FECHA DE ALTA
SELECT NOM_ZONA, NOM_EMPLEADO
  FROM ZONAS JOIN EMPLE_PARQUE ON EMPLE_PARQUE.DNI_EMPLE=ZONAS.DNI_ENCARGADO
    ORDER BY EMPLE_PARQUE.NOM_EMPLEADO;
    
--PARA AVERIAS DE 2022, MOSTRAR NOMBRE DE EMPLE QUE ARREGLO, NOMBRE DE ATRACCION Y PRESUPUESTO A LA ZONA
SELECT NOM_EMPLEADO, NOM_ATRACCION, PRESUPUESTO
  FROM ATRACCIONES, AVERIAS_PARQUE, EMPLE_PARQUE, ZONAS
    WHERE ATRACCIONES.COD_ATRACCION=AVERIAS_PARQUE.COD_ATRACCION
      AND AVERIAS_PARQUE.DNI_EMPLE=EMPLE_PARQUE.DNI_EMPLE
      AND ATRACCIONES.NOM_ZONA=ZONAS.NOM_ZONA
      AND FECHA_ARREGLO LIKE '%22';
      
--DNI DE EMPLEADO QUE TIENE QUE ARREGLAR ATRACCIONES, NOMBRE DE ATRACCION, ZONA Y ENCARGADO
SELECT EMPLE_PARQUE.DNI_EMPLE, NOM_ATRACCION, ATRACCIONES.NOM_ZONA, EMPLE_PARQUE.NOM_EMPLEADO
  FROM ATRACCIONES, AVERIAS_PARQUE, EMPLE_PARQUE, ZONAS
    WHERE ATRACCIONES.COD_ATRACCION=AVERIAS_PARQUE.COD_ATRACCION
      AND AVERIAS_PARQUE.DNI_EMPLE=EMPLE_PARQUE.DNI_EMPLE
      AND ATRACCIONES.NOM_ZONA=ZONAS.NOM_ZONA
      AND AVERIAS_PARQUE.FECHA_ARREGLO IS NULL;