--TABLA DE DEPART Y EMPLE

--EMPLEADOS QUE ESTÁN EN EL MISMO DEPARTAMENTO QUE GIL
SELECT APELLIDO
  FROM EMPLE
    WHERE DEPT_NO = (SELECT DEPT_NO
                      FROM EMPLE
                        WHERE APELLIDO = 'GIL')
        AND APELLIDO <> 'GIL';

--EMPLEADOS CON SALARIO SUPERIOR AL DE TOVAR
SELECT APELLIDO, SALARIO
  FROM EMPLE
    WHERE SALARIO > (SELECT SALARIO
                      FROM EMPLE
                        WHERE APELLIDO = 'TOVAR')
        AND APELLIDO <> 'TOVAR';
--EMPLEADOS QUE TIENEN EL MISMO OFICIO QUE MARTIN O GANAN MENOS QUE ALONSO
SELECT APELLIDO, OFICIO, SALARIO
  FROM EMPLE
    WHERE (OFICIO = (SELECT OFICIO FROM EMPLE WHERE APELLIDO = 'MARTIN')
      OR SALARIO < (SELECT SALARIO FROM EMPLE WHERE APELLIDO = 'ALONSO'))
        AND APELLIDO <> 'MARTIN'
          AND APELLIDO <> 'ALONSO';
--APELLIDO Y SALARIO DE LOS EMPLEADOS QUE TIENEN POR RESPONSABLE A QUIEN SE APELLIDA ROJO
SELECT APELLIDO, SALARIO, RESPONSABLE
  FROM EMPLE
    WHERE RESPONSABLE = (SELECT EMP_NO FROM EMPLE WHERE APELLIDO = 'ROJO');
--EMPLEADOS EN EL MISMO DEPARTAMENTO QUE GIL Y TIENEN SU MISMO OFICIO Y SALARIO
SELECT APELLIDO, DEPT_NO, OFICIO, SALARIO
  FROM EMPLE
    WHERE DEPT_NO = (SELECT DEPT_NO FROM EMPLE WHERE APELLIDO = 'GIL')
      AND OFICIO = (SELECT OFICIO FROM EMPLE WHERE APELLIDO = 'GIL')
      AND SALARIO = (SELECT SALARIO FROM EMPLE WHERE APELLIDO = 'GIL')
      AND APELLIDO <> 'GIL';
      
--TABLA DE ALUMNOS, ASIGNATURAS Y NOTAS

--DATOS DE LOS ALUMNOS QUE VIVEN EN LA MISMA POBLACIÓN QUE LUIS
SELECT *
  FROM ALUMNOS
    WHERE POBLA = (SELECT POBLA FROM ALUMNOS WHERE APENOM='Cerrato Vela, Luis')
    AND APENOM <> 'Cerrato Vela, Luis';
--NOMBRE DE LOS ALUMNOS QUE HAN APROBADO TODO
SELECT APENOM, NOTA
  FROM ALUMNOS JOIN NOTAS ON ALUMNOS.DNI=NOTAS.DNI
    WHERE ALUMNOS.DNI NOT IN (SELECT NOTAS.DNI FROM NOTAS WHERE NOTA<5);
--NOMBRE DE LAS ASIGNATURAS QUE NO HAN TENIDO NINGÚN 6
SELECT NOMBRE, NOTA
  FROM NOTAS JOIN ASIGNATURAS ON NOTAS.COD=ASIGNATURAS.COD
    WHERE NOTAS.COD NOT IN (SELECT NOTAS.COD FROM NOTAS WHERE NOTA=6);
--VISUALIZAR LOS NOMBRE DE ASIGNATURAS QUE NO TENGAN SUSPENSOS
SELECT DISTINCT NOMBRE
  FROM NOTAS JOIN ASIGNATURAS ON NOTAS.COD=ASIGNATURAS.COD
    WHERE NOTAS.COD NOT IN (SELECT NOTAS.COD FROM NOTAS WHERE NOTA<5);
--VISUALIZAR LOS NOMBRES DE LOS ALUMNOS DE MADRID QUE TENGA ALGUNA ASIGNATURA SUSPENSA
SELECT DISTINCT APENOM
  FROM ALUMNOS JOIN NOTAS ON ALUMNOS.DNI=NOTAS.DNI
    WHERE POBLA = 'Madrid'
      AND NOTAS.DNI NOT IN (SELECT DNI FROM NOTAS WHERE NOTA<5);
--MOSTRAR LOS NOMBRES DE LOS ALUMNOS QUE TENGA LA MISMA NOTA QUE TIENE MARÍA EN MARCAS EN ALGUNA ASIGNATURA
SELECT APENOM, NOMBRE
  FROM ALUMNOS, NOTAS, ASIGNATURAS
    WHERE ALUMNOS.DNI=NOTAS.DNI
      AND NOTAS.COD=ASIGNATURAS.COD
      AND NOTA=(SELECT NOTA 
                    FROM ASIGNATURAS, NOTAS, ALUMNOS
                      WHERE  ALUMNOS.DNI=NOTAS.DNI
                        AND NOTAS.COD=ASIGNATURAS.COD
                        AND APENOM='Díaz Fernández, María'
                        AND NOMBRE='Marcas')
      AND APENOM<>'Díaz Fernández, María';
--MOSTRAR LOS NOMBRES DE LOS ALUMNOS QUE TIENEN EN PROGRAMACIÓN LA MISMA NOTA QUE HA SACADO LUIS EN PROGRAMACIÓN
SELECT APENOM, NOMBRE, NOTA
  FROM ALUMNOS, NOTAS, ASIGNATURAS
    WHERE ALUMNOS.DNI=NOTAS.DNI
      AND NOTAS.COD=ASIGNATURAS.COD
      AND NOTA=(SELECT NOTA 
                    FROM ASIGNATURAS, NOTAS, ALUMNOS
                      WHERE  ALUMNOS.DNI=NOTAS.DNI
                        AND NOTAS.COD=ASIGNATURAS.COD
                        AND APENOM='Cerrato Vela, Luis'
                        AND NOMBRE='Programación')
      AND NOMBRE='Programación';

--TABLA DE PARQUES

SELECT * FROM ATRACCIONES;
SELECT * FROM AVERIAS_PARQUE;
SELECT * FROM EMPLE_PARQUE;
SELECT * FROM ZONAS;

--NOMBRE DE ATRACCIONES QUE ESTAN EN LA MISMA ZONA QUE LEJANO OESTE
SELECT NOM_ATRACCION, ATRACCIONES.NOM_ZONA
  FROM ATRACCIONES JOIN ZONAS ON ATRACCIONES.NOM_ZONA=ZONAS.NOM_ZONA
    WHERE ATRACCIONES.NOM_ZONA=(SELECT NOM_ZONA FROM ATRACCIONES WHERE NOM_ATRACCION='Lejano Oeste')
      AND NOM_ATRACCION <> 'Lejano Oeste';
      
--NOMBRE DE LAS ATRACCIONES QUE NO HAN TENIDO AVERIAS
SELECT NOM_ATRACCION
  FROM ATRACCIONES
    WHERE COD_ATRACCION NOT IN (SELECT COD_ATRACCION FROM AVERIAS_PARQUE);
    
--NOMBRE DE ATRACCIONES QUE NO ESTÁN AVERIADAS
SELECT DISTINCT NOM_ATRACCION
  FROM ATRACCIONES
    WHERE COD_ATRACCION NOT IN (SELECT COD_ATRACCION FROM AVERIAS_PARQUE)
      OR COD_ATRACCION IN (SELECT COD_ATRACCION FROM AVERIAS_PARQUE WHERE FECHA_ARREGLO IS NOT NULL);
      
--EMPLEADOS QUE NO HAN INICIADO ARREGLOS EN EL AÑO 2023
SELECT DISTINCT NOM_EMPLEADO
  FROM EMPLE_PARQUE
    WHERE DNI_EMPLE NOT IN (SELECT DNI_EMPLE FROM AVERIAS_PARQUE WHERE FECHA_ARREGLO LIKE '%2023%');
    
  
    

                                            