--JARED JAMES LLOYD BUENO--

--EJERCICIO 1
SELECT UPPER(NOM_ATRACCION)"NOMBRE DEL ATRACCION", SUBSTR(COD_ATRACCION,1,1)||'-'||SUBSTR(COD_ATRACCION,2,3) "CODIGO", ROUND(CAPACIDAD-(CAPACIDAD*0.10),1) "CAPACIDAD REDUCIDO",
PRESUPUESTO, SUBSTR(DNI_ENCARGADO,-1,1) "LETRA DEL DNI DEL ENCARGADO"
  FROM ATRACCIONES JOIN ZONAS ON ZONAS.NOM_ZONA = ATRACCIONES.NOM_ZONA
    WHERE ATRACCIONES.NOM_ZONA = 'Infantil' OR ATRACCIONES.NOM_ZONA = 'Agua';
    
--EJERCICIO 2
SELECT TRUNC(FECHA_ARREGLO-FECHA_FALLA)"DIAS_ESTROPEADAS", ATRACCIONES.NOM_ZONA, NOM_ATRACCION, NOM_EMPLEADO "NOM_ENCARGADO"
FROM AVERIAS_PARQUE, ATRACCIONES, EMPLE_PARQUE, ZONAS
WHERE AVERIAS_PARQUE.COD_ATRACCION=ATRACCIONES.COD_ATRACCION AND EMPLE_PARQUE.DNI_EMPLE=ZONAS.DNI_ENCARGADO AND ATRACCIONES.NOM_ZONA=ZONAS.NOM_ZONA
  AND FECHA_ARREGLO IS NOT NULL
  AND COSTE_AVERIA BETWEEN 1000 AND 8000
    ORDER BY ATRACCIONES.NOM_ZONA, NOM_ATRACCION;
  
--EJERCICIO 3
SELECT COUNT (ATRACCIONES.COD_ATRACCION) "TOTAL Nº DE AVERÍAS", COUNT(AVERIAS_PARQUE.FECHA_FALLA)-COUNT(AVERIAS_PARQUE.FECHA_ARREGLO)"ATRACCIONES SIN ARREGLAR",
  MAX(COSTE_AVERIA)"MAYOR COSTE", MAX(FECHA_FALLA)"ULTIMA AVERÍA"
    FROM AVERIAS_PARQUE JOIN ATRACCIONES ON AVERIAS_PARQUE.COD_ATRACCION = ATRACCIONES.COD_ATRACCION
     WHERE NOM_ZONA = 'Infantil'
       AND AVERIAS_PARQUE.COD_ATRACCION IN (SELECT COD_ATRACCION FROM ATRACCIONES WHERE NOM_ZONA='Infantil');
       
--EJERCICIO 4
SELECT NOM_EMPLEADO, TRUNC((SYSDATE-ALTA_EMPRESA)/365.25)"AÑOS EN LA EMPRESA"
  FROM EMPLE_PARQUE
    WHERE ALTA_EMPRESA < (SELECT ALTA_EMPRESA FROM EMPLE_PARQUE WHERE NOM_EMPLEADO LIKE '%Ana%')
      OR TRUNC((SYSDATE-ALTA_EMPRESA)/365.25) < 8;
      
--EJERCICIO 5
SELECT NOM_ATRACCION
  FROM ATRACCIONES
    WHERE CAPACIDAD = (SELECT MAX(CAPACIDAD) FROM ATRACCIONES WHERE NOM_ZONA='Infantil')
      AND NOM_ZONA = 'Infantil';
      
--EJERCICIO 6
SELECT NOM_EMPLEADO
  FROM EMPLE_PARQUE
    WHERE DNI_EMPLE NOT IN (SELECT DNI_ENCARGADO FROM ZONAS);