DROP TABLE INCIDENCIAS;
DROP TABLE ALQUILERES;
DROP TABLE CLIENTES_INMUEBLES;
DROP TABLE INMUEBLES;
DROP TABLE PROPIETARIOS;

CREATE TABLE PROPIETARIOS
(
  NIF VARCHAR2(9) NOT NULL UNIQUE,
  NUM_PROPIETARIO NUMBER PRIMARY KEY,
  NOMBRE VARCHAR2(30),
  AÑO_ALTA NUMBER(4) DEFAULT TO_CHAR(SYSDATE,'YYYY'),
  TELEFONO NUMBER,
  EMAIL VARCHAR2(30)
);

CREATE TABLE INMUEBLES
(
  REFERENCIA VARCHAR2(30),
  TIPO  CHAR(1),
  DIRECCION VARCHAR2(30),
  NUM_HAB NUMBER,
  NUM_SERVICIOS NUMBER,
  JARDIN CHAR(1) DEFAULT 'N',
  PISCINA CHAR(1) DEFAULT 'N',
  DUEÑO NUMBER REFERENCES PROPIETARIOS,
  PRECIO_DIA NUMBER(*,2),
  
  CONSTRAINT PK_INMUEBLES PRIMARY KEY (REFERENCIA),
  CONSTRAINT CK_REF CHECK ((SUBSTR(REFERENCIA,1,2)=TIPO||'-') AND (REGEXP_LIKE(SUBSTR(REFERENCIA,3),'[0-9]'))),
  CONSTRAINT CK_TIPO_INMUEBLES CHECK (TIPO IN ('A','C')),
  CONSTRAINT CK_NUM_HAB CHECK (NUM_HAB>=0 AND NUM_HAB<=10),
  CONSTRAINT CK_NUM_SERVICIOS CHECK (NUM_SERVICIOS>=0 AND NUM_HAB<=10),
  CONSTRAINT CK_JARDIN CHECK (JARDIN IN ('S','N')),
  CONSTRAINT CK_PISCINA CHECK (PISCINA IN ('S','N')),
  CONSTRAINT CK_DIRECCION CHECK (LENGTH(DIRECCION) >=5 )
);

CREATE TABLE CLIENTES_INMUEBLES
(
  DNI VARCHAR2(30),
  NOMBRE VARCHAR2(30),
  DIRECCION VARCHAR2(30),
  TELEFONO NUMBER,
  EMAIL VARCHAR2(30),
  
  CONSTRAINT PK_CLIENTES_INMUEBLES PRIMARY KEY (DNI)
);

CREATE TABLE ALQUILERES
(
  NUM_FACTURA NUMBER,
  REFERENCIA VARCHAR2(30) REFERENCES INMUEBLES NOT NULL,
  FECHA_ENTRADA DATE NOT NULL,
  FECHA_SALIDA  DATE NOT NULL,
  DNI_CLIENTE VARCHAR2(30) REFERENCES CLIENTES NOT NULL,
  PRECIO  NUMBER(*,2) NOT NULL,
  
  CONSTRAINT PK_ALQUILERES PRIMARY KEY (NUM_FACTURA),
  CONSTRAINT UNIQ_ALQUILERES UNIQUE (REFERENCIA, FECHA_ENTRADA)
);

ALTER TABLE CLIENTES
ADD FECHA_ALTA DATE DEFAULT SYSDATE;

ALTER TABLE INMUEBLES
DROP CONSTRAINT CK_NUM_HAB;

CREATE TABLE INCIDENCIAS
(
NUM_FACTURA NUMBER REFERENCES ALQUILERES,
NUM_INCIDENCIA NUMBER,
COMENTARIO VARCHAR2(30),
ESTADO CHAR(1),
CONSTRAINT PK_INCIDENCIAS PRIMARY KEY (NUM_INCIDENCIA)
);