--INSERTAR UN NUEVO DEPARTAMENTO CON CÓDIGO 55, NOMBRE RECURSOS Y LOCALIDAD MADRID
INSERT INTO DEPART VALUES (55,'RECURSOS','MADRID');

--INSERTAR UN EMPLEADO EN EL 55 CON NÚMERO DE EMPLEADO 8000, APELLIDO ESCUDERO, SALARIO 2230, OFICIO GESTOR Y FECHA DE ALTA LA DEL SISTEMA
INSERT INTO EMPLE
SELECT 8000,'ESCUDERO','GESTOR',NULL,SYSDATE,2230,NULL,DEPT_NO
  FROM DEPART
    WHERE DEPT_NO=55;

--INSERTAR UN EMPLEADO CON CODIGO 8001, APELLIDO VERDIN, FECHA DE ALTA DE AYER, Y EL RESTO DE LOS DATOS LOS DEL EMPLEADO 7654
INSERT INTO EMPLE
SELECT 8001,'VERDIN',OFICIO,RESPONSABLE,SYSDATE-1,SALARIO,COMISION,DEPT_NO
  FROM EMPLE
    WHERE EMP_NO=7654;

--INSERTAR UN EMPLEADO CON NUMERO 9050, APELLIDO TUYO, OFICIO BECARIO, RESPONSABLE EL NÚMERO DE SALA, FECHA DE ALTA DENTRO DE UNA SEMANA, SALARIO MITAD DE SALA, COMISION NULA
--Y DEPARTAMENTO DE SALA
INSERT INTO EMPLE
SELECT 9050, 'BUENO', 'BECARIO', EMP_NO, SYSDATE+7, SALARIO/2, NULL, DEPT_NO
  FROM EMPLE
    WHERE APELLIDO='SALA';

--INSERTAR UN NUEVO DEPARTAMENTO CODIGO 65 CON NOMBRE I+D Y LOCALIDAD EL DEPARTAMENTO EN EL QUE TRABAJA EL EMPLEADO GIL
INSERT INTO DEPART
SELECT 65, 'I+D', LOC
  FROM EMPLE JOIN DEPART ON EMPLE.DEPT_NO = DEPART.DEPT_NO
    WHERE APELLIDO='GIL';

--INSERTAR UN EMPLEADO CON CODIGO 9055, APELLIDO DE TU COMPAÑERO, OFICIO BECARIO, RESPONSABLE EL NUMERO DE EMPLEADO DE SALA, FECHA DE ALTA DEL SISTEMA SALARIO LA MITAD DE ARROYO
--COMISION NULA Y DEPARTAMENTO EL DE SALA
INSERT INTO EMPLE
SELECT 9055, 'COMPAÑERO', 'BECARIO', EMP_NO, SYSDATE, (SELECT SALARIO FROM EMPLE WHERE APELLIDO='ARROYO')/2, NULL, DEPT_NO
  FROM EMPLE
    WHERE APELLIDO='SALA';
