--MOSTRAR EL MES Y AÑO EN EL QUE ENTRÓ A TRABAJAR EL PRESIDENTE
SELECT TO_CHAR(FECHA_ALTA, 'MM/YYYY') "MES Y AÑO DE ALTA"
  FROM EMPLE
    WHERE OFICIO='PRESIDENTE';
    
--MOSTRAR LOS EMPLEADOS QUE ENTRARON A TRABAJAR EN VIERNES
SELECT APELLIDO
  FROM EMPLE
    WHERE TO_CHAR(FECHA_ALTA, 'DAY') LIKE '%VIERNES%';
    
--MOSTRAR EL MES (EN NÚMERO Y EN LETRA) EN EL QUE ENTRARON A TRABAJAR LOS EMPLEADOS QUE ENTRARON EN EL AÑO 2017
SELECT TO_CHAR(FECHA_ALTA, 'MM, MONTH')
  FROM EMPLE
    WHERE TO_CHAR(FECHA_ALTA, 'YYYY')=2017;
    
--MOSTRAR APELLIDO, FECHAS DE ALTA, AÑOS QUE LLEVAN EN LA EMPRESA, Y LOCALIDAD EN LA QUE TRABAJAN LOS EMPLEADOS QUE ENTRARON A TRABAJAR EN NOV O DEC
SELECT APELLIDO, FECHA_ALTA, TRUNC((SYSDATE-FECHA_ALTA)/365.25)"AÑOS EN LA EMPRESA", LOC
  FROM EMPLE JOIN DEPART ON EMPLE.DEPT_NO = DEPART.DEPT_NO
    WHERE TO_CHAR(FECHA_ALTA, 'MONTH') LIKE '%NOVIEMBRE%'
      OR TO_CHAR(FECHA_ALTA, 'MONTH') LIKE '%DICIEMBRE%';
      
--MOSTRAR CUANTOS TRIENIOS LLEVAN EN LA EMPRESA LOS EMPLEADOS DE LOS DEPARTAMENTOS DE INVESTIGACION Y VENTAS
SELECT  TRUNC((SYSDATE-FECHA_ALTA)/(365.25*3))"TRIENIOS COMPLETOS", TRUNC((SYSDATE-FECHA_ALTA)/365.25)"AÑOS"
  FROM EMPLE JOIN DEPART ON EMPLE.DEPT_NO = DEPART.DEPT_NO
    WHERE DNOMBRE = 'INVESTIGACION'
      OR DNOMBRE = 'VENTAS';
      
--MOSTRAR UNA PAGA ESPECIAL QUE SE VA A DAR A LOS EMPLEADOS QUE LLEVAN MÁS DE 10 AÑOS EN LA EMPRESA Y QUE CONSISTE EN 400 EUROS POR AÑO TRABAJADO
SELECT 400*(TRUNC((SYSDATE-FECHA_ALTA)/365.25))"PAGA ESPECIAL", TRUNC((SYSDATE-FECHA_ALTA)/365.25)"AÑOS EN LA EMPRESA"
  FROM EMPLE
    WHERE TRUNC((SYSDATE-FECHA_ALTA)/365.25)>10;
    
--MOSTRAR CUÁNTOS AÑOS LLEVA TRABAJANDO EL EMPLEADO MÁS ANTIGUO DE LA EMPRESA
SELECT TRUNC((SYSDATE-FECHA_ALTA)/365.25) "AÑOS EN LA EMPRESA"
  FROM EMPLE
    WHERE TRUNC((SYSDATE-FECHA_ALTA)/365.25) = (SELECT MAX(TRUNC((SYSDATE-FECHA_ALTA)/365.25)) FROM EMPLE);
  
--MOSTRAR CUANTOS AÑOS LLEVARÁN LOS EMPLEADOS DE VENTAS EL DÍA 30/11/2023
SELECT TRUNC((TO_DATE('30/11/2023','DD/MM/YYYY')-FECHA_ALTA)/365.25)"AÑOS"
  FROM EMPLE JOIN DEPART ON EMPLE.DEPT_NO = DEPART.DEPT_NO
    WHERE DNOMBRE='VENTAS';
    
--TABLA DE PARQUE

--MOSTRAR HORA Y MINUTO LA ATRACCION CATARATAS LOCAS Y 3 PRIMERAS LETRAS DE SU ZONA
SELECT TO_CHAR(FECHA_FALLA, 'HH24:MI')"HORA ESTROPEO" , SUBSTR(NOM_ZONA,1,3)
  FROM ATRACCIONES JOIN AVERIAS_PARQUE ON AVERIAS_PARQUE.COD_ATRACCION = ATRACCIONES.COD_ATRACCION
    WHERE NOM_ATRACCION = 'Cataratas Locas' ;
    
--MOSTRAR CUANTOS DIAS ESTUVIERON SIN FUNCIONAR LAS ATRACCIONES QUE ESTÁN ARREGLADAS Y EL NOMBRE DE LA ATRACCION, EL NOMBRE DE LA ZONA Y EL PRESUPUESTO
SELECT TRUNC(FECHA_ARREGLO-FECHA_FALLA)"DIAS ESTROPEADAS", NOM_ATRACCION, ATRACCIONES.NOM_ZONA, PRESUPUESTO
  FROM ATRACCIONES, AVERIAS_PARQUE, ZONAS
    WHERE ATRACCIONES.COD_ATRACCION=AVERIAS_PARQUE.COD_ATRACCION AND ZONAS.NOM_ZONA=ATRACCIONES.NOM_ZONA
      AND FECHA_ARREGLO IS NOT NULL;
      
--MOSTRAR CUANTOS DIAS LLEVAN AVERIADAS LAS ATRACCIONES QUE ESTAN SIN ARREGLAR Y MOSTRAR EL NOMBRE DEL ENCARGADO DE LA ZONA Y EL DNI DEL EMPLEADO QUE LO TIENE QUE ARREGLAR
SELECT TRUNC(SYSDATE-FECHA_FALLA)"DIAS ESTROPEAEDAS", NOM_EMPLEADO"ENCARGADO DE LA ZONA", AVERIAS_PARQUE.DNI_EMPLE"EL QUE REPARA"
  FROM ATRACCIONES, AVERIAS_PARQUE, ZONAS, EMPLE_PARQUE
    WHERE ATRACCIONES.COD_ATRACCION=AVERIAS_PARQUE.COD_ATRACCION AND ZONAS.NOM_ZONA=ATRACCIONES.NOM_ZONA AND EMPLE_PARQUE.DNI_EMPLE=ZONAS.DNI_ENCARGADO
      AND FECHA_ARREGLO IS NULL;
      
--MOSTRAR LA SUMA DEL COSTE DE LAS AVERIAS ARREGLADAS A PARTIR DE LAS SEIS DE LA TARDE
SELECT *
  FROM AVERIAS_PARQUE
    WHERE FECHA_ARREGLO IS NOT NULL
      AND TO_CHAR(FECHA_ARREGLO, 'HH24')>='18';
      
--MOSTRAR LOS DATOS DE LAS AVERÍAS PRODUCIDAS UN DÍA 12 DE CUALQUIER MES DEL AÑO 2023
SELECT *
  FROM AVERIAS_PARQUE
    WHERE TO_CHAR(FECHA_FALLA,'DD')=12
      AND TO_CHAR(FECHA_FALLA,'YYYY')=2023;
      
--MOSTRAR LOS DATOS DE LA AVERÍA QUE MÁS HA TARDADO EN ARREGLARSE DE LA ZONA INFANTIL
SELECT *
  FROM AVERIAS_PARQUE
    WHERE TRUNC(FECHA_ARREGLO-FECHA_FALLA)=(SELECT MAX(TRUNC(FECHA_ARREGLO-FECHA_FALLA)) FROM AVERIAS_PARQUE)
      AND COD_ATRACCION IN (SELECT COD_ATRACCION FROM ATRACCIONES WHERE NOM_ZONA='Infantil');