--PROCEDIMIENTO INFORMES_TALLER

--EL PROCEDIMIENTO RECIBE UN INDICADOR (1,2,3)
--SEA 1
  --MUESTRA LOS CLIENTES, SUS DATOS, Y POR CADA CLIENTE SUS COCHES (DOBLE CURSOR)
--SEA 2
  --MUESTRA LOS MECANICOS, SUS DATOS, Y POR CADA MECANICO SUS ARREGLOS (DOBLE CURSOR)
--SEA 3
  --RESUMEN DE COCHES Y SUS ARREGLOS (SELECT CON GROUP BY)
  
--SE PUEDE USAR FUNCIONES O OTROS PROCEDIMIENTOSN DENTRO DE INFORMES_TALLER

--SE ENTREGARÁ:
  --UN ENUNCIADO CON TODO LO QUE QUEREMOS QUE HAGA NUESTRO PROCEDIMIENTO
  --EJEMPLOS DE EJECUCION
  --EL CÓDIGO DE LOS PROCEDIMIENTOS
  
  --SE ENTREGA TODO CHULO EN UN PDF Y EL CÓDIGO EN UN SCRIPT .SQL
  
CREATE OR REPLACE PROCEDURE INFORMES_TALLER(PINDICADOR NUMBER)
AS
BEGIN
  CASE PINDICADOR
    WHEN 1 THEN PROC1_INFORME;
    WHEN 2 THEN PROC2_INFORME;
    WHEN 3 THEN PROC3_INFORME;
    WHEN 4 THEN PROC4_INFORME;
  ELSE
    DBMS_OUTPUT.PUT_LINE('EL INDICADOR INTRODUCIDO NO ES VÁLIDO');
  END CASE;
END;

CREATE OR REPLACE PROCEDURE PROC1_INFORME
AS
  CURSOR CUR_CLIENTE IS
   SELECT *
     FROM CLIENTES_TALLER;
  VNCLIENTE COCHES_TALLER.NCLIENTE%TYPE;
  CURSOR CUR_COCHES IS
    SELECT *
      FROM COCHES_TALLER
        WHERE NCLIENTE = VNCLIENTE;
BEGIN
  DBMS_OUTPUT.PUT_LINE(RPAD('NCLIENTE',10)||RPAD('NOMBRE',18)||RPAD('DIRECCION',18)||RPAD('TELEFONO',15)||RPAD('FECHA_ALTA',10));
  DBMS_OUTPUT.PUT_LINE('------------------------------------------------------------------------');
  FOR I IN CUR_CLIENTE LOOP
    VNCLIENTE:=I.NCLIENTE;
    DBMS_OUTPUT.PUT_LINE(RPAD(I.NCLIENTE,10)||RPAD(I.NOMBRE,18)||RPAD(I.DIRECCION,18)||RPAD(I.TELEFONO,15)||RPAD(I.FECHA_ALTA,10));
    FOR J IN CUR_COCHES LOOP
      DBMS_OUTPUT.PUT_LINE(RPAD(' ',5)||RPAD(' ',18)||RPAD(J.MODELO,18)||RPAD(J.MATRICULA,15)||RPAD(J.AÑO_MATRICULA,10));
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('------------------------------------------------------------------------');
  END LOOP;
END;

CREATE OR REPLACE PROCEDURE PROC2_INFORME
AS
  CURSOR CUR_MECANICOS IS
   SELECT *
     FROM MECANICOS;
  VNEMPLEADO MECANICOS.NEMPLEADO%TYPE;
  CURSOR CUR_ARREGLOS IS
    SELECT *
      FROM ARREGLOS
        WHERE NEMPLEADO = VNEMPLEADO;
BEGIN
  DBMS_OUTPUT.PUT_LINE(RPAD('NEMPLEADO',10)||RPAD('NOMBRE',18)||RPAD('DIRECCION',20)||RPAD('TELEFONO',15)||RPAD('FECHA_NAC',10)||RPAD('FECHA_ING',10)||RPAD('FUNCION',18));
  DBMS_OUTPUT.PUT_LINE('-------------------------------------------------------------------------------------------------');
  FOR I IN CUR_MECANICOS LOOP
    VNEMPLEADO:=I.NEMPLEADO;
    DBMS_OUTPUT.PUT_LINE(RPAD(I.NEMPLEADO,10)||RPAD(I.NOMBRE,18)||RPAD(I.DIRECCION,20)||RPAD(I.TELEFONO,15)||RPAD(I.FECHA_NAC,10)||RPAD(I.FECHA_ING,10)||RPAD(I.FUNCION,18));
    FOR J IN CUR_ARREGLOS LOOP
      DBMS_OUTPUT.PUT_LINE(RPAD(' ',5)||RPAD(J.MATRICULA,18)||RPAD(J.IMPORTE,10)||RPAD(J.FECHA_ENTRADA,10)||RPAD(J.FECHA_SALIDA,10));
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('-------------------------------------------------------------------------------------------------');
  END LOOP;
END;

CREATE OR REPLACE PROCEDURE PROC3_INFORME
AS
  CURSOR CUR_COCHES_RESUMEN IS
    SELECT COUNT(*) NUM_ARREGLOS, MATRICULA
      FROM ARREGLOS
      GROUP BY MATRICULA;
BEGIN
  FOR I IN CUR_COCHES_RESUMEN LOOP
    DBMS_OUTPUT.PUT_LINE('EL COCHE '||I.MATRICULA||' TIENE '||I.NUM_ARREGLOS||' ARREGLOS.');
  END LOOP;
END;

CREATE OR REPLACE PROCEDURE PROC4_INFORME
AS
  CURSOR CUR_CLIENTES IS
    SELECT *
      FROM CLIENTES_TALLER;
  VNCLIENTE CLIENTES_TALLER.NCLIENTE%TYPE;
  CURSOR CUR_COCHES IS 
    SELECT *
      FROM COCHES_TALLER
        WHERE NCLIENTE=VNCLIENTE;
  VMATRICULA COCHES_TALLER.MATRICULA%TYPE;
  CURSOR CUR_ARREGLOS IS
    SELECT *
      FROM ARREGLOS
        WHERE MATRICULA=VMATRICULA;
BEGIN
  DBMS_OUTPUT.PUT_LINE(RPAD('NCLIENTE',10)||RPAD('NOMBRE',18)||RPAD('DIRECCION',18)||RPAD('TELEFONO',15)||RPAD('FECHA_ALTA',10));
    DBMS_OUTPUT.PUT_LINE('----------------------------------------------------------------');
  FOR I IN CUR_CLIENTES LOOP
    VNCLIENTE:=I.NCLIENTE;
    DBMS_OUTPUT.PUT_LINE(RPAD(I.NCLIENTE,10)||RPAD(I.NOMBRE,18)||RPAD(I.DIRECCION,18)||RPAD(I.TELEFONO,15)||RPAD(I.FECHA_ALTA,10));
    DBMS_OUTPUT.PUT_LINE(RPAD(' ',2)||LPAD('--->',18)||RPAD('MODELO',18)||RPAD('MATRICULA',15)||RPAD('AÑO_MATRICULA',15));
    FOR J IN CUR_COCHES LOOP
      VMATRICULA:=J.MATRICULA;
      DBMS_OUTPUT.PUT_LINE(RPAD(' ',2)||LPAD('--->',18)||RPAD(J.MODELO,18)||RPAD(J.MATRICULA,15)||RPAD(J.AÑO_MATRICULA,15));
      DBMS_OUTPUT.PUT_LINE(RPAD(' ',5)||RPAD(' ',18)||RPAD('IMPORTE',10)||RPAD('FECHA_ENTRADA',15)||RPAD('FECHA_SALIDA',15));
      FOR K IN CUR_ARREGLOS LOOP
        DBMS_OUTPUT.PUT_LINE(RPAD(' ',5)||RPAD(' ',18)||RPAD(K.IMPORTE||'€',10)||RPAD(K.FECHA_ENTRADA,15)||RPAD(K.FECHA_SALIDA,15));
      END LOOP;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('----------------------------------------------------------------');
  END LOOP;
END;

EXECUTE INFORMES_TALLER(1); --PROCEDIMIENTO 1
EXECUTE INFORMES_TALLER(2); --PROCEDIMIENTO 2
EXECUTE INFORMES_TALLER(3); --PROCEDIMIENTO 3
EXECUTE INFORMES_TALLER(4); --PROCEDIMIENTO 4
EXECUTE INFORMES_TALLER(5); --INDICADOR INCORRECTO

--SELECT DE LAS TABLAS
SELECT * FROM CLIENTES_TALLER;
SELECT * FROM MECANICOS;
SELECT * FROM COCHES_TALLER;
SELECT * FROM ARREGLOS;