--AÑADIR UNA NUEVA ASIGNATURA CON CÓDIGO 1 MÁS QUE LA ÚLTIMA QUE EXISTA Y DE NOMBRE FOL

INSERT INTO ASIGNATURAS
SELECT MAX(COD)+1, 'FOL'
FROM ASIGNATURAS;

--DAR DE ALTA A UN NUEVO ALUMNO CON TUS DATOS DNI INVENTADO, APENOM EL TUYO, TELÉFONO A NULO Y LA DIRECCIÓN Y POBLA DE ELENA

INSERT INTO ALUMNOS
SELECT '12345678A', 'Tilla Quemada, Aitor', DIREC, POBLA, 663663663
FROM ALUMNOS
WHERE APENOM LIKE '%Elena%';

--SE HA ESTROPEADO LA NORIA, ACABA DE AVERIARSE, NO SABEMOS CUANDO SE ARREGLARÁ NI LO QUE VA A COSTAR. LA AVERIA SE LA VAMOS A ASIGNAR AL EMPLEADO 3455344J

INSERT INTO AVERIAS_PARQUE
SELECT COD_ATRACCION, SYSDATE, NULL, NULL, '3455344J'
FROM ATRACCIONES
WHERE COD_ATRACCION = (SELECT COD_ATRACCION FROM ATRACCIONES WHERE NOM_ATRACCION LIKE 'La Noria');

--PONER EL SALARIO LA MITAD DEL SALARIO DEL PRESIDENTE A SANCHEZ

UPDATE EMPLE
SET SALARIO=(SELECT SALARIO/2 FROM EMPLE WHERE OFICIO = 'PRESIDENTE')
WHERE APELLIDO='SANCHEZ';