CREATE OR REPLACE PROCEDURE TABLITA_EJEMPLO
AS
  TYPE TABLA_NUM IS TABLE OF NUMBER INDEX BY BINARY_INTEGER;
  TABLA1 TABLA_NUM;
  TABLA2 TABLA_NUM;
  INDICE NUMBER;
BEGIN
  FOR I IN 1..10 LOOP
    TABLA1 (I):=I*10;
    DBMS_OUTPUT.PUT_LINE(TABLA1 (I));
  END LOOP;
  
  FOR I IN 1..5 LOOP
    INDICE:=I*2;
    TABLA2(INDICE) := INDICE * INDICE;
  END LOOP;
  
  DBMS_OUTPUT.PUT_LINE(TABLA2.FIRST);
  DBMS_OUTPUT.PUT_LINE(TABLA2.LAST);
  DBMS_OUTPUT.PUT_LINE(TABLA2.COUNT);
  
  INDICE := TABLA2.LAST; --SI SE QUIERE EMPEZAR POR EL PRINCIPIO SE USA TABLA2.FIRST Y TABLA2.NEXT
  
  WHILE INDICE IS NOT NULL LOOP
      DBMS_OUTPUT.PUT_LINE(INDICE ||' '||TABLA2(INDICE));
      INDICE:=TABLA2.PRIOR(INDICE);
  END LOOP;  
END;

EXECUTE TABLITA_EJEMPLO;