DROP TABLE VIAJES;
DROP TABLE TRAYECTOS;
DROP TABLE COCHES;
DROP TABLE CONDUCTORES;

CREATE TABLE CONDUCTORES
(
DNI VARCHAR2(9) NOT NULL,
NOMBRE VARCHAR2(30) NOT NULL UNIQUE,
ALTA_EMPRESA DATE DEFAULT SYSDATE NOT NULL,
CONSTRAINT PK_CONDUCTORES PRIMARY KEY (DNI),
CONSTRAINT CK_DNI CHECK (SUBSTR(DNI,-1)=UPPER(SUBSTR(DNI,-1)))
);

CREATE TABLE COCHES
(
MATRICULA VARCHAR2(7),
NUM_PLAZAS NUMBER,
ULT_REVISION DATE,
CONSTRAINT PK_MATRICULA PRIMARY KEY (MATRICULA),
CONSTRAINT CK_MATRICULA CHECK (REGEXP_LIKE(MATRICULA,'^[0-9]{4}\-[A-Z]{3}$')),
CONSTRAINT CK_NUM_PLAZAS CHECK (NUM_PLAZAS>0)
);

CREATE TABLE TRAYECTOS
(
ORIGEN VARCHAR2(20) NOT NULL,
DESTINO VARCHAR2(20) NOT NULL,
PRECIO NUMBER(6,2) NOT NULL,
KMS NUMBER NOT NULL,
CONSTRAINT PK_TRAYECTOS PRIMARY KEY (ORIGEN,DESTINO),
CONSTRAINT CK_TRAYECTO CHECK (ORIGEN!=DESTINO),
CONSTRAINT CK_PRECIO CHECK (PRECIO>=10 AND PRECIO<=120),
CONSTRAINT CK_KMS CHECK (KMS>=5)
);

CREATE TABLE VIAJES
(
ORIGEN VARCHAR2(30),
DESTINO VARCHAR2(30),
FH_IDA DATE,
MATRICULA VARCHAR2(7),
HORA_VUELTA CHAR(4) NOT NULL,
DNI VARCHAR2(9) REFERENCES CONDUCTORES,
BILLETES_VENDIDOS NUMBER,
CONSTRAINT PK_VIAJES PRIMARY KEY (MATRICULA, FH_IDA),
CONSTRAINT FK_TRAYECTOS FOREIGN KEY (ORIGEN, DESTINO) REFERENCES TRAYECTOS,
CONSTRAINT FK_MATRICULA_VIAJES FOREIGN KEY (MATRICULA) REFERENCES COCHES,
CONSTRAINT CK_HORA_VUELTA CHECK (HORA_VUELTA>TO_CHAR(FH_IDA,'HH24MI'))
);