--DE LA CALLE DE ESTRECHO
--FECHA Y HORA DE VISITA (DIA//MES HORA:MINUTOS - DIA DE LA SEMANA EN LETRA)
SELECT TO_CHAR(FH_VISITA, 'dd//mm hh24:mi-dy'), ANIMALES.NOMBRE||' '||SUBSTR(TFNO_CONTACTO,1,5)||'****', SUBSTR(DUEÑOS.ALTA_CLINICA, 4,4), NVL(DIAGNOSTICO, 'NO CONSTA')
  FROM VISITAS, DUEÑOS, ANIMALES
    WHERE VISITAS.IDENT_ANIMAL=ANIMALES.IDENT_ANIMAL AND ANIMALES.DNI_DUEÑO=DUEÑOS.DNI
      AND DIRECCION LIKE '%Estrecho%'
    ORDER BY VISITAS.IDENT_ANIMAL, FH_VISITA;
    
--MOSTRAR POR CADA ANIMAL SU IDENTIFICADOR Y SU ESPECIE, TOTAL DINERO GASTADO EN LAS VISITAS, CUANTAS VISITAS HAN TENIDO Y CON CUANTOS VETERINARIOS DISTINTOS
--HACERLO SOLO SI EL GASTO SUPERA A LOS 60 EUROS
SELECT ANIMALES.IDENT_ANIMAL, ESPECIE, SUM(PRECIO)"PRECIO TOTAL", COUNT(FH_VISITA)"Nº DE VISITAS", COUNT(VISITAS.NUMCOLEGIADO)"Nº DE VET"
  FROM VISITAS, DUEÑOS, ANIMALES, VETERINARIOS
    WHERE VISITAS.IDENT_ANIMAL=ANIMALES.IDENT_ANIMAL AND ANIMALES.DNI_DUEÑO=DUEÑOS.DNI AND VETERINARIOS.NUMCOLEGIADO=VISITAS.NUMCOLEGIADO
    GROUP BY ANIMALES.IDENT_ANIMAL, ESPECIE
      HAVING SUM(PRECIO)>60;
      
--MOSTRAR EL VETERINARIO QUE MÁS HA HECHO VISITAS A PERROS
SELECT VETERINARIOS.NOMBRE, COUNT(*)
  FROM VISITAS, VETERINARIOS, ANIMALES
    WHERE VISITAS.IDENT_ANIMAL=ANIMALES.IDENT_ANIMAL AND VETERINARIOS.NUMCOLEGIADO=VISITAS.NUMCOLEGIADO
    AND ESPECIE='PERRO'
    GROUP BY VETERINARIOS.NOMBRE, ESPECIE
      HAVING COUNT(*)=(SELECT MAX(COUNT(*)) 
                          FROM VISITAS JOIN ANIMALES ON VISITAS.IDENT_ANIMAL = ANIMALES.IDENT_ANIMAL
                            WHERE ESPECIE='PERRO' 
                              GROUP BY VISITAS.NUMCOLEGIADO, ESPECIE);
    
--MOSTRAR LOS ANIMALES QUE SON DE LA MISMA RAZA QUE JUK O FILOMENA. SACAD NOMBRE, ESPECIE, RAZA Y EDAD. TAMBIÉN SACAR EL DÍA DE SU CUMPLEAÑOS EN EL 2023 Y QUE SEMANA CAERÁ
SELECT ANIMALES.NOMBRE, ESPECIE, RAZA, TRUNC((SYSDATE-FECHA_NACIMIENTO)/365.25)"EDAD", TO_CHAR(TO_DATE(TO_CHAR(FECHA_NACIMIENTO,'DD-MM-')||2023),'DD-MM-YYYY DY')
  FROM ANIMALES
    WHERE (RAZA = (SELECT RAZA FROM ANIMALES WHERE NOMBRE='JUK')
      OR RAZA = (SELECT RAZA FROM ANIMALES WHERE NOMBRE='FILOMENA'))
        AND NOMBRE <> 'JUK' 
         AND NOMBRE <> 'FILOMENA';